POST http://localhost:8080/DingdingTest/testController
Content-Type: application/json

{
  "test": "1",
  "test2": 2
}

###
POST http://dingdinemo-atgi-serverllication-ttkrsxcneu.cn-hangzhou.fcapp.run/testControlNoHandler
Content-Type: application/json

{
  "test": "1123",
  "test2": 232
}

###
